URL="https://sourceforge.net/projects/nitruxos/files/Release/ISO/nitrux-nx-desktop-REPLACE_VERSION-amd64.iso"
TYPE=file
CONTENTS="\
boot/initramfs|initrd
boot/kernel|vmlinuz
casper/filesystem.squashfs|filesystem.squashfs"
EXTRACT_INITRD="true"
INITRD_NAME="initrd"
INITRD_TYPE="zstd"
