URL="https://pop-iso.sfo2.cdn.digitaloceanspaces.com/REPLACE_VERSION/amd64/nvidia/9/pop-os_REPLACE_VERSION_amd64_nvidia_9.iso"
TYPE=file
CONTENTS="\
casper_pop-os_21.04_*/filesystem.squashfs|filesystem.squashfs
casper_pop-os_21.04_*/initrd.gz|initrd
casper_pop-os_21.04_*/vmlinuz.efi|vmlinuz"
EXTRACT_INITRD="true"
INITRD_NAME="initrd"
INITRD_TYPE="lz4"
